server:
  port: 8080

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/cs?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    prefix: classpath:/templates/
    encoding: utf-8
  devtools:
    restart:
      enabled: true

mybatis:
  mapper-locations: classpath:mapping/**/*Mapper.xml
  type-aliases-package: com.entity

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: countSql
  page-size-zero: true


#showSql
logging:
  level:
    com:
      example:
        mapper : debug

